[![Made by Mr.Sahraoui](https://img.shields.io/badge/Made%20by-Mr.Sahraoui-orange)](https://digitalpro.dev)
![NLP](https://img.shields.io/badge/NLP-TP%20%202-orange)

<table style="width: 100%;">
<tr>
<td style="width: 50%; text-align: right; vertical-align: middle;">
<img src="https://github.com/gitpizzanow/dummy-files/blob/main/tp1nlp.jpg?raw=true" width="150">
</td>
<td style="width: 50%; text-align: left; vertical-align: middle;">

##  (NLP)   | Text Manipulation &Fake News Classification
> [SERIE](https://tp1-nlp-ing4.netlify.app/)


* *Text cleaning*
* *Text normalization*
* *Text tokenization*


> [DATA](https://www.kaggle.com/datasets/emineyetm/fake-news-detection-datasets)

</td>
</tr>
</table>

In [20]:
!pip install spacy

Requirement already satisfied: spacy in c:\users\pc\anaconda3\lib\site-packages (3.8.11)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (8.3.10)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (0.24.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (2.1.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (2.10.3)
Requirement already satisfied: jinja2 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in c:\users\pc\anaconda3\lib\site-packages (from spacy) (72.1.0)
Requirement already satisfied: packaging>=20.0 in c:\users\pc\anaconda3\lib\site-packages (from spacy) (24.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\pc\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in c:\users\pc\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.27.1)
Requirement already satisfied: typing-extensions>=4.12.2 in c:\users\pc\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\pc\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\pc\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\pc\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\pc\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.10.5)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in c:\users\pc\anaconda3\lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.3)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in c:\users\pc\anaconda3\lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: colorama in c:\users\pc\anaconda3\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: typer>=0.24.0 in c:\users\pc\anaconda3\lib\site-packages (from typer-slim<1.0.0,>=0.3.0->spacy) (0.24.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in c:\users\pc\anaconda3\lib\site-packages (from weasel<0.5.0,>=0.4.2->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in c:\users\pc\anaconda3\lib\site-packages (from weasel<0.5.0,>=0.4.2->spacy) (7.5.1)
Requirement already satisfied: wrapt in c:\users\pc\anaconda3\lib\site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy) (1.17.0)
Requirement already satisfied: click>=8.2.1 in c:\users\pc\anaconda3\lib\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\pc\anaconda3\lib\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (1.5.0)
Requirement already satisfied: rich>=12.3.0 in c:\users\pc\anaconda3\lib\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\pc\anaconda3\lib\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\pc\anaconda3\lib\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\pc\anaconda3\lib\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\pc\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\pc\anaconda3\lib\site-packages (from jinja2->spacy) (3.0.2)

In [21]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
      --------------------------------------- 0.3/12.8 MB ? eta -:--:--
      --------------------------------------- 0.3/12.8 MB ? eta -:--:--
      --------------------------------------- 0.3/12.8 MB ? eta -:--:--
      --------------------------------------- 0.3/12.8 MB ? eta -:--:--
      --------------------------------------- 0.3/12.8 MB ? eta -:--:--
      --------------------------------------- 0.3/12.8 MB ? eta -:--:--
     - ------------------------------------- 0.5/12.8 MB 212.9 kB/s eta 0:00:58
     - ------------------------------------- 0.5/12.8 MB 212.9 kB/s eta 0:00:58
     - ------------------------------------- 0.5/12.8 MB 212.9 kB/s eta 0:00:58
     - ------------------------------------- 0.5/12.8 MB 212.9 kB/s eta 0:00:58
     - ------------------------------------- 0.5/12.8 MB 212.9 kB/s eta 0:00:58
     -- ------------------------------------ 0.8/12.8 MB 235.9 kB/s eta 0:00:51
     -- ------------------------------------ 0.8/12.8 MB 235.9 kB/s eta 0:00:51
     -- ------------------------------------ 0.8/12.8 MB 235.9 kB/s eta 0:00:51
     -- ------------------------------------ 0.8/12.8 MB 235.9 kB/s eta 0:00:51
     -- ------------------------------------ 0.8/12.8 MB 235.9 kB/s eta 0:00:51
     --- ----------------------------------- 1.0/12.8 MB 238.9 kB/s eta 0:00:50
     --- ----------------------------------- 1.0/12.8 MB 238.9 kB/s eta 0:00:50
     --- ----------------------------------- 1.0/12.8 MB 238.9 kB/s eta 0:00:50
     --- ----------------------------------- 1.0/12.8 MB 238.9 kB/s eta 0:00:50
     --- ----------------------------------- 1.0/12.8 MB 238.9 kB/s eta 0:00:50
     --- ----------------------------------- 1.3/12.8 MB 241.7 kB/s eta 0:00:48
     --- ----------------------------------- 1.3/12.8 MB 241.7 kB/s eta 0:00:48
     --- ----------------------------------- 1.3/12.8 MB 241.7 kB/s eta 0:00:48
     --- ----------------------------------- 1.3/12.8 MB 241.7 kB/s eta 0:00:48
     --- ----------------------------------- 1.3/12.8 MB 241.7 kB/s eta 0:00:48
     --- ----------------------------------- 1.3/12.8 MB 241.7 kB/s eta 0:00:48
     --- ----------------------------------- 1.3/12.8 MB 241.7 kB/s eta 0:00:48
     --- ----------------------------------- 1.3/12.8 MB 241.7 kB/s eta 0:00:48
     ---- ---------------------------------- 1.6/12.8 MB 213.2 kB/s eta 0:00:53
     ---- ---------------------------------- 1.6/12.8 MB 213.2 kB/s eta 0:00:53
     ---- ---------------------------------- 1.6/12.8 MB 213.2 kB/s eta 0:00:53
     ---- ---------------------------------- 1.6/12.8 MB 213.2 kB/s eta 0:00:53
     ---- ---------------------------------- 1.6/12.8 MB 213.2 kB/s eta 0:00:53
     ----- --------------------------------- 1.8/12.8 MB 220.6 kB/s eta 0:00:50
     ----- --------------------------------- 1.8/12.8 MB 220.6 kB/s eta 0:00:50
     ----- --------------------------------- 1.8/12.8 MB 220.6 kB/s eta 0:00:50
     ----- --------------------------------- 1.8/12.8 MB 220.6 kB/s eta 0:00:50
     ------ -------------------------------- 2.1/12.8 MB 228.2 kB/s eta 0:00:47
     ------ -------------------------------- 2.1/12.8 MB 228.2 kB/s eta 0:00:47
     ------ -------------------------------- 2.1/12.8 MB 228.2 kB/s eta 0:00:47
     ------- ------------------------------- 2.4/12.8 MB 240.3 kB/s eta 0:00:44
     ------- ------------------------------- 2.4/12.8 MB 240.3 kB/s eta 0:00:44
     ------- ------------------------------- 2.4/12.8 MB 240.3 kB/s eta 0:00:44
     ------- ------------------------------- 2.6/12.8 MB 250.7 kB/s eta 0:00:41
     ------- ------------------------------- 2.6/12.8 MB 250.7 kB/s eta 0:00:41
     ------- ------------------------------- 2.6/12.8 MB 250.7 kB/s eta 0:00:41
     -------- ------------------------------ 2.9/12.8 MB 261.2 kB/s eta 0:00:38
     -------- ------------------------------ 2.9/12.8 MB 261.2 kB/s eta 0:00:38
     -------- ------------------------------ 2.9/12.8 MB 261.2 kB/s eta 0:00:38
     --------- ----------------------------- 3.1/12.8 MB 271.4 kB/s eta 0:00:36
     --------- ----------------------------- 3.1/12.8 MB 271.4 kB/s eta 0:00:36
     --------- ----------------------------- 3.1/12.8 MB 271.4 kB/s eta 0:00:36
     ---------- ---------------------------- 3.4/12.8 MB 277.6 kB/s eta 0:00:34
     ---------- ---------------------------- 3.4/12.8 MB 277.6 kB/s eta 0:00:34
     ---------- ---------------------------- 3.4/12.8 MB 277.6 kB/s eta 0:00:34
     ---------- ---------------------------- 3.4/12.8 MB 277.6 kB/s eta 0:00:34
     ----------- --------------------------- 3.7/12.8 MB 281.0 kB/s eta 0:00:33
     ----------- --------------------------- 3.7/12.8 MB 281.0 kB/s eta 0:00:33
     ----------- --------------------------- 3.7/12.8 MB 281.0 kB/s eta 0:00:33
     ----------- --------------------------- 3.9/12.8 MB 287.0 kB/s eta 0:00:31
     ----------- --------------------------- 3.9/12.8 MB 287.0 kB/s eta 0:00:31
     ----------- --------------------------- 3.9/12.8 MB 287.0 kB/s eta 0:00:31
     ------------ -------------------------- 4.2/12.8 MB 291.6 kB/s eta 0:00:30
     ------------ -------------------------- 4.2/12.8 MB 291.6 kB/s eta 0:00:30
     ------------ -------------------------- 4.2/12.8 MB 291.6 kB/s eta 0:00:30
     ------------ -------------------------- 4.2/12.8 MB 291.6 kB/s eta 0:00:30
     ------------- ------------------------- 4.5/12.8 MB 292.2 kB/s eta 0:00:29
     ------------- ------------------------- 4.5/12.8 MB 292.2 kB/s eta 0:00:29
     ------------- ------------------------- 4.5/12.8 MB 292.2 kB/s eta 0:00:29
     -------------- ------------------------ 4.7/12.8 MB 296.0 kB/s eta 0:00:28
     -------------- ------------------------ 4.7/12.8 MB 296.0 kB/s eta 0:00:28
     -------------- ------------------------ 4.7/12.8 MB 296.0 kB/s eta 0:00:28
     --------------- ----------------------- 5.0/12.8 MB 300.7 kB/s eta 0:00:27
     --------------- ----------------------- 5.0/12.8 MB 300.7 kB/s eta 0:00:27
     --------------- ----------------------- 5.0/12.8 MB 300.7 kB/s eta 0:00:27
     --------------- ----------------------- 5.2/12.8 MB 306.3 kB/s eta 0:00:25
     --------------- ----------------------- 5.2/12.8 MB 306.3 kB/s eta 0:00:25
     --------------- ----------------------- 5.2/12.8 MB 306.3 kB/s eta 0:00:25
     ---------------- ---------------------- 5.5/12.8 MB 308.6 kB/s eta 0:00:24
     ---------------- ---------------------- 5.5/12.8 MB 308.6 kB/s eta 0:00:24
     ---------------- ---------------------- 5.5/12.8 MB 308.6 kB/s eta 0:00:24
     ---------------- ---------------------- 5.5/12.8 MB 308.6 kB/s eta 0:00:24
     ----------------- --------------------- 5.8/12.8 MB 309.8 kB/s eta 0:00:23
     ----------------- --------------------- 5.8/12.8 MB 309.8 kB/s eta 0:00:23
     ----------------- --------------------- 5.8/12.8 MB 309.8 kB/s eta 0:00:23
     ----------------- --------------------- 5.8/12.8 MB 309.8 kB/s eta 0:00:23
     ----------------- --------------------- 5.8/12.8 MB 309.8 kB/s eta 0:00:23
     ------------------ -------------------- 6.0/12.8 MB 302.8 kB/s eta 0:00:23
     ------------------ -------------------- 6.0/12.8 MB 302.8 kB/s eta 0:00:23
     ------------------ -------------------- 6.0/12.8 MB 302.8 kB/s eta 0:00:23
     ------------------- ------------------- 6.3/12.8 MB 308.4 kB/s eta 0:00:22
     ------------------- ------------------- 6.3/12.8 MB 308.4 kB/s eta 0:00:22
     ------------------- ------------------- 6.3/12.8 MB 308.4 kB/s eta 0:00:22
     ------------------- ------------------- 6.6/12.8 MB 309.6 kB/s eta 0:00:21
     ------------------- ------------------- 6.6/12.8 MB 309.6 kB/s eta 0:00:21
     ------------------- ------------------- 6.6/12.8 MB 309.6 kB/s eta 0:00:21
     ------------------- ------------------- 6.6/12.8 MB 309.6 kB/s eta 0:00:21
     -------------------- ------------------ 6.8/12.8 MB 310.7 kB/s eta 0:00:20
     -------------------- ------------------ 6.8/12.8 MB 310.7 kB/s eta 0:00:20
     -------------------- ------------------ 6.8/12.8 MB 310.7 kB/s eta 0:00:20
     -------------------- ------------------ 6.8/12.8 MB 310.7 kB/s eta 0:00:20
     -------------------- ------------------ 6.8/12.8 MB 310.7 kB/s eta 0:00:20
     --------------------- ----------------- 7.1/12.8 MB 306.6 kB/s eta 0:00:19
     --------------------- ----------------- 7.1/12.8 MB 306.6 kB/s eta 0:00:19
     --------------------- ----------------- 7.1/12.8 MB 306.6 kB/s eta 0:00:19
     --------------------- ----------------- 7.1/12.8 MB 306.6 kB/s eta 0:00:19
     --------------------- ----------------- 7.1/12.8 MB 306.6 kB/s eta 0:00:19
     --------------------- ----------------- 7.1/12.8 MB 306.6 kB/s eta 0:00:19
     --------------------- ----------------- 7.1/12.8 MB 306.6 kB/s eta 0:00:19
     --------------------- ----------------- 7.1/12.8 MB 306.6 kB/s eta 0:00:19
     --------------------- ----------------- 7.1/12.8 MB 306.6 kB/s eta 0:00:19
     ---------------------- ---------------- 7.3/12.8 MB 291.4 kB/s eta 0:00:19
     ---------------------- ---------------- 7.3/12.8 MB 291.4 kB/s eta 0:00:19
     ---------------------- ---------------- 7.3/12.8 MB 291.4 kB/s eta 0:00:19
     ---------------------- ---------------- 7.3/12.8 MB 291.4 kB/s eta 0:00:19
     ---------------------- ---------------- 7.3/12.8 MB 291.4 kB/s eta 0:00:19
     ---------------------- ---------------- 7.3/12.8 MB 291.4 kB/s eta 0:00:19
     ---------------------- ---------------- 7.3/12.8 MB 291.4 kB/s eta 0:00:19
     ---------------------- ---------------- 7.3/12.8 MB 291.4 kB/s eta 0:00:19
     ----------------------- --------------- 7.6/12.8 MB 282.6 kB/s eta 0:00:19
     ----------------------- --------------- 7.6/12.8 MB 282.6 kB/s eta 0:00:19
     ----------------------- --------------- 7.6/12.8 MB 282.6 kB/s eta 0:00:19
     ----------------------- --------------- 7.6/12.8 MB 282.6 kB/s eta 0:00:19
     ----------------------- --------------- 7.6/12.8 MB 282.6 kB/s eta 0:00:19
     ----------------------- --------------- 7.6/12.8 MB 282.6 kB/s eta 0:00:19
     ----------------------- --------------- 7.6/12.8 MB 282.6 kB/s eta 0:00:19
     ----------------------- --------------- 7.9/12.8 MB 277.2 kB/s eta 0:00:18
     ----------------------- --------------- 7.9/12.8 MB 277.2 kB/s eta 0:00:18
     ----------------------- --------------- 7.9/12.8 MB 277.2 kB/s eta 0:00:18
     ----------------------- --------------- 7.9/12.8 MB 277.2 kB/s eta 0:00:18
     ----------------------- --------------- 7.9/12.8 MB 277.2 kB/s eta 0:00:18
     ----------------------- --------------- 7.9/12.8 MB 277.2 kB/s eta 0:00:18
     ----------------------- --------------- 7.9/12.8 MB 277.2 kB/s eta 0:00:18
     ------------------------ -------------- 8.1/12.8 MB 271.1 kB/s eta 0:00:18
     ------------------------ -------------- 8.1/12.8 MB 271.1 kB/s eta 0:00:18
     ------------------------ -------------- 8.1/12.8 MB 271.1 kB/s eta 0:00:18
     ------------------------ -------------- 8.1/12.8 MB 271.1 kB/s eta 0:00:18
     ------------------------ -------------- 8.1/12.8 MB 271.1 kB/s eta 0:00:18
     ------------------------ -------------- 8.1/12.8 MB 271.1 kB/s eta 0:00:18
     ------------------------ -------------- 8.1/12.8 MB 271.1 kB/s eta 0:00:18
     ------------------------ -------------- 8.1/12.8 MB 271.1 kB/s eta 0:00:18
     ------------------------ -------------- 8.1/12.8 MB 271.1 kB/s eta 0:00:18
     ------------------------- ------------- 8.4/12.8 MB 265.1 kB/s eta 0:00:17
     ------------------------- ------------- 8.4/12.8 MB 265.1 kB/s eta 0:00:17
     ------------------------- ------------- 8.4/12.8 MB 265.1 kB/s eta 0:00:17
     ------------------------- ------------- 8.4/12.8 MB 265.1 kB/s eta 0:00:17
     ------------------------- ------------- 8.4/12.8 MB 265.1 kB/s eta 0:00:17
     -------------------------- ------------ 8.7/12.8 MB 264.3 kB/s eta 0:00:16
     -------------------------- ------------ 8.7/12.8 MB 264.3 kB/s eta 0:00:16
     -------------------------- ------------ 8.7/12.8 MB 264.3 kB/s eta 0:00:16
     -------------------------- ------------ 8.7/12.8 MB 264.3 kB/s eta 0:00:16
     --------------------------- ----------- 8.9/12.8 MB 265.1 kB/s eta 0:00:15
     --------------------------- ----------- 8.9/12.8 MB 265.1 kB/s eta 0:00:15
     --------------------------- ----------- 8.9/12.8 MB 265.1 kB/s eta 0:00:15
     --------------------------- ----------- 8.9/12.8 MB 265.1 kB/s eta 0:00:15
     --------------------------- ----------- 9.2/12.8 MB 267.0 kB/s eta 0:00:14
     --------------------------- ----------- 9.2/12.8 MB 267.0 kB/s eta 0:00:14
     --------------------------- ----------- 9.2/12.8 MB 267.0 kB/s eta 0:00:14
     ---------------------------- ---------- 9.4/12.8 MB 278.4 kB/s eta 0:00:13
     ---------------------------- ---------- 9.4/12.8 MB 278.4 kB/s eta 0:00:13
     ---------------------------- ---------- 9.4/12.8 MB 278.4 kB/s eta 0:00:13
     ----------------------------- --------- 9.7/12.8 MB 280.9 kB/s eta 0:00:12
     ----------------------------- --------- 9.7/12.8 MB 280.9 kB/s eta 0:00:12
     ----------------------------- --------- 9.7/12.8 MB 280.9 kB/s eta 0:00:12
     ----------------------------- -------- 10.0/12.8 MB 282.7 kB/s eta 0:00:11
     ----------------------------- -------- 10.0/12.8 MB 282.7 kB/s eta 0:00:11
     ----------------------------- -------- 10.0/12.8 MB 282.7 kB/s eta 0:00:11
     ----------------------------- -------- 10.0/12.8 MB 282.7 kB/s eta 0:00:11
     ------------------------------ ------- 10.2/12.8 MB 283.9 kB/s eta 0:00:10
     ------------------------------ ------- 10.2/12.8 MB 283.9 kB/s eta 0:00:10
     ------------------------------ ------- 10.2/12.8 MB 283.9 kB/s eta 0:00:10
     ------------------------------ ------- 10.2/12.8 MB 283.9 kB/s eta 0:00:10
     ------------------------------- ------ 10.5/12.8 MB 285.3 kB/s eta 0:00:09
     ------------------------------- ------ 10.5/12.8 MB 285.3 kB/s eta 0:00:09
     ------------------------------- ------ 10.5/12.8 MB 285.3 kB/s eta 0:00:09
     ------------------------------- ------ 10.7/12.8 MB 284.6 kB/s eta 0:00:08
     ------------------------------- ------ 10.7/12.8 MB 284.6 kB/s eta 0:00:08
     ------------------------------- ------ 10.7/12.8 MB 284.6 kB/s eta 0:00:08
     ------------------------------- ------ 10.7/12.8 MB 284.6 kB/s eta 0:00:08
     ------------------------------- ------ 10.7/12.8 MB 284.6 kB/s eta 0:00:08
     ------------------------------- ------ 10.7/12.8 MB 284.6 kB/s eta 0:00:08
     ------------------------------- ------ 10.7/12.8 MB 284.6 kB/s eta 0:00:08
     -------------------------------- ----- 11.0/12.8 MB 274.7 kB/s eta 0:00:07
     -------------------------------- ----- 11.0/12.8 MB 274.7 kB/s eta 0:00:07
     -------------------------------- ----- 11.0/12.8 MB 274.7 kB/s eta 0:00:07
     --------------------------------- ---- 11.3/12.8 MB 272.6 kB/s eta 0:00:06
     --------------------------------- ---- 11.3/12.8 MB 272.6 kB/s eta 0:00:06
     --------------------------------- ---- 11.3/12.8 MB 272.6 kB/s eta 0:00:06
     --------------------------------- ---- 11.3/12.8 MB 272.6 kB/s eta 0:00:06
     ---------------------------------- --- 11.5/12.8 MB 272.4 kB/s eta 0:00:05
     ---------------------------------- --- 11.5/12.8 MB 272.4 kB/s eta 0:00:05
     ---------------------------------- --- 11.5/12.8 MB 272.4 kB/s eta 0:00:05
     ----------------------------------- -- 11.8/12.8 MB 273.5 kB/s eta 0:00:04
     ----------------------------------- -- 11.8/12.8 MB 273.5 kB/s eta 0:00:04
     ----------------------------------- -- 11.8/12.8 MB 273.5 kB/s eta 0:00:04
     ----------------------------------- -- 11.8/12.8 MB 273.5 kB/s eta 0:00:04
     ----------------------------------- -- 12.1/12.8 MB 272.6 kB/s eta 0:00:03
     ----------------------------------- -- 12.1/12.8 MB 272.6 kB/s eta 0:00:03
     ----------------------------------- -- 12.1/12.8 MB 272.6 kB/s eta 0:00:03
     ----------------------------------- -- 12.1/12.8 MB 272.6 kB/s eta 0:00:03
     ----------------------------------- -- 12.1/12.8 MB 272.6 kB/s eta 0:00:03
     ----------------------------------- -- 12.1/12.8 MB 272.6 kB/s eta 0:00:03
     ------------------------------------ - 12.3/12.8 MB 266.3 kB/s eta 0:00:02
     ------------------------------------ - 12.3/12.8 MB 266.3 kB/s eta 0:00:02
     -------------------------------------  12.6/12.8 MB 267.4 kB/s eta 0:00:01
     -------------------------------------  12.6/12.8 MB 267.4 kB/s eta 0:00:01
     -------------------------------------  12.6/12.8 MB 267.4 kB/s eta 0:00:01
     -------------------------------------- 12.8/12.8 MB 270.0 kB/s eta 0:00:00
[+] Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [24]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [32]:
import string

punctuations = list(string.punctuation) # Get all punctuation : !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [39]:
import pandas as pd

fake_df = pd.read_csv(r'C:\Users\pc\Downloads\Fake.csv')
true_df = pd.read_csv(r'C:\Users\pc\Downloads\True.csv')

In [40]:
fake_df.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [41]:
true_df.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [42]:
fake_df['label'] = 0
true_df['label'] = 1

In [43]:
true_df_cols = true_df.columns
fake_df_cols = fake_df.columns

print (true_df_cols)
print (fake_df_cols)

Index(['title', 'text', 'subject', 'date', 'label'], dtype='object')
Index(['title', 'text', 'subject', 'date', 'label'], dtype='object')

In [44]:
data = pd.concat([fake_df, true_df], ignore_index=True)
data = data.sample(frac=1, random_state=42).reset_index(drop=True) #shuffle the dataset

data.head()

,title,text,subject,date,label
0,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",0
1,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"April 5, 2017",1
2,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,"September 27, 2017",1
3,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",0
4,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,"June 24, 2016",1

In [95]:
X = data['text'].tolist()[:50]
y = data['label'].tolist()[:50]
print(X[0])
print("--------------------------------------------------------------------------------------------")
print(X[40])

21st Century Wire says Ben Stein, reputable professor from, Pepperdine University (also of some Hollywood fame appearing in TV shows and films such as Ferris Bueller s Day Off) made some provocative statements on Judge Jeanine Pirro s show recently. While discussing the halt that was imposed on President Trump s Executive Order on travel. Stein referred to the judgement by the 9th Circuit Court in Washington state as a  Coup d tat against the executive branch and against the constitution.  Stein went on to call the Judges in Seattle  political puppets  and the judiciary  political pawns. Watch the interview below for the complete statements and note the stark contrast to the rhetoric of the leftist media and pundits who neglect to note that no court has ever blocked any Presidential orders in immigration in the past or discuss the legal efficacy of the halt or the actual text of the Executive Order.READ MORE TRUMP NEWS AT: 21st Century Wire Trump FilesSUPPORT OUR WORK BY SUBSCRIBING & BECOMING A MEMBER @21WIRE.TV
--------------------------------------------------------------------------------------------
BAGHDAD (Reuters) - A Russian Islamic State fighter was sentenced to death by hanging in Iraq on Tuesday, authorities said, a rare conviction of a foreign militant on terrorism charges. The unnamed man was captured after running out of ammunition in western Mosul, a spokesman for Iraq s Supreme Judicial Council said in a statement.  The Russian was a member of Daesh operating in Mosul since 2015,  he added, using an Arabic acronym for the Sunni Muslim militant group.  Thousands of foreigners have been fighting for Islamic State in Iraq and Syria.   Security and aid officials told Reuters over the weekend that Iraqi authorities were holding 1,400 foreign wives and children of suspected militants - most from Turkey, others from former Soviet states including Tajikistan, Azerbaijan and Russia. Iraqi forces, backed by U.S.-led coalition allies and Kurds, retook Mosul in July following the group s occupation of the country s second largest city in 2014. The Sunni militant group still controls territory in Iraq and is expected to revert to more conventional insurgent tactics such as bombings as its self-proclaimed caliphate falls apart.

![ ](https://img.shields.io/badge/Text_normalization-red)

In [49]:
!pip install num2words

Collecting num2words
  Downloading num2words-0.5.14-py3-none-any.whl.metadata (13 kB)
Collecting docopt>=0.6.2 (from num2words)
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Downloading num2words-0.5.14-py3-none-any.whl (163 kB)
Building wheels for collected packages: docopt
  Building wheel for docopt (setup.py): started
  Building wheel for docopt (setup.py): finished with status 'done'
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13775 sha256=b4fc111cf2a01e8bc003b0d131b095719151275cc88a8c83e12a898d725fefed
  Stored in directory: c:\users\pc\appdata\local\pip\cache\wheels\0b\1d\03\175286677fb5a1341cc3e4755bf8ec0ed08f3329afd67446b0
Successfully built docopt
Installing collected packages: docopt, num2words

   -------------------- ------------------- 1/2 [num2words]
   -------------------- ------------------- 1/2 [num2words]
   -------------------- ------------------- 1/2 [num2words]
   -------------------- ------------------- 1/2 [num2words]
   ---------------------------------------- 2/2 [num2words]

Successfully installed docopt-0.6.2 num2words-0.5.14

  DEPRECATION: Building 'docopt' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'docopt'. Discussion can be found at https://github.com/pypa/pip/issues/6334

![ ](https://img.shields.io/badge/Number_to_words_conversion%20%20-blue)

In [80]:
from num2words import num2words
import re
X2=[re.sub(r'\b(\d+)(st|nd|rd|th)\b', lambda m: num2words(int(m.group(1)), to='ordinal'), text) for text in X]#goup(1) je prends seulement les chiffres
X2 = [re.sub(r'\b\d+\b', lambda m: num2words(int(m.group())), text) for text in X2]
print(X2[0])
print("-----------------------------------------------------------------------------------")
print(X2[40])

twenty-first Century Wire says Ben Stein, reputable professor from, Pepperdine University (also of some Hollywood fame appearing in TV shows and films such as Ferris Bueller s Day Off) made some provocative statements on Judge Jeanine Pirro s show recently. While discussing the halt that was imposed on President Trump s Executive Order on travel. Stein referred to the judgement by the ninth Circuit Court in Washington state as a  Coup d tat against the executive branch and against the constitution.  Stein went on to call the Judges in Seattle  political puppets  and the judiciary  political pawns. Watch the interview below for the complete statements and note the stark contrast to the rhetoric of the leftist media and pundits who neglect to note that no court has ever blocked any Presidential orders in immigration in the past or discuss the legal efficacy of the halt or the actual text of the Executive Order.READ MORE TRUMP NEWS AT: twenty-first Century Wire Trump FilesSUPPORT OUR WORK BY SUBSCRIBING & BECOMING A MEMBER @21WIRE.TV
-----------------------------------------------------------------------------------
(Reuters) - Georgia Governor Nathan Deal issued a mandatory evacuation order on Thursday for the state s coast, including historic Savannah, as deadly Hurricane Irma rolled toward Florida and the southeastern United States. The evacuation order for areas east of Interstate ninety-five and some areas to its west takes effect Saturday at eight a.m., Deal said in a statement. The governor also authorized up to five,zero Georgia National Guard members to respond to the storm and expanded a state of emergency to thirty southeast Georgia counties. The order affects the cities of Savannah and Brunswick in Georgia, which has not been hit by a Category three hurricane or higher since one thousand, eight hundred and ninety-eight, according to WSB-TV.  I encourage all Georgians in our coastal areas that could be impacted by this storm to evacuate the area as soon as possible,  Deal said in a statement. Irma, one of the most powerful Atlantic storms in a century, plowed past the Dominican Republic toward Haiti on Thursday after devastating a string of Caribbean islands and killing at least ten people. Irma will likely hit Florida as a powerful Category four storm on Sunday, with storm surges and flooding beginning within the next forty-eight hours, according to the NHC. Gas shortages in the  Miami-Fort Lauderdale area worsened on Thursday, with sales up to five times the norm. The storm s exact path is uncertain, but it could affect Georgia and the Carolinas early next week.

![ ](https://img.shields.io/badge/drop_stop_words%20%20-blue)

In [104]:
X3 = []
for text in X2:
    text_sp = nlp(text)
    tokens = [t for t in text_sp if not t.is_stop]
    X3.append(tokens)
print (X3[0])

[-, Century, Wire, says, Ben, Stein, ,, reputable, professor, ,, Pepperdine, University, (, Hollywood, fame, appearing, TV, shows, films, Ferris, Bueller, s, Day, ), provocative, statements, Judge, Jeanine, Pirro, s, recently, ., discussing, halt, imposed, President, Trump, s, Executive, Order, travel, ., Stein, referred, judgement, ninth, Circuit, Court, Washington, state,  , Coup, d, tat, executive, branch, constitution, .,  , Stein, went, Judges, Seattle,  , political, puppets,  , judiciary,  , political, pawns, ., Watch, interview, complete, statements, note, stark, contrast, rhetoric, leftist, media, pundits, neglect, note, court, blocked, Presidential, orders, immigration, past, discuss, legal, efficacy, halt, actual, text, Executive, Order, ., READ, TRUMP, NEWS, :, -, Century, Wire, Trump, FilesSUPPORT, WORK, SUBSCRIBING, &, MEMBER, @21WIRE.TV]

![ ](https://img.shields.io/badge/drop_punctuations%20%20-blue)

In [130]:
X4 = []
for text in X3:
    tokens = []
    for token in text:
        if token.text not in punctuations :
            tokens.append(token.text)#.text!
    X4.append(tokens)
print(X4[0])

['Century', 'Wire', 'says', 'Ben', 'Stein', 'reputable', 'professor', 'Pepperdine', 'University', 'Hollywood', 'fame', 'appearing', 'TV', 'shows', 'films', 'Ferris', 'Bueller', 's', 'Day', 'provocative', 'statements', 'Judge', 'Jeanine', 'Pirro', 's', 'recently', 'discussing', 'halt', 'imposed', 'President', 'Trump', 's', 'Executive', 'Order', 'travel', 'Stein', 'referred', 'judgement', 'ninth', 'Circuit', 'Court', 'Washington', 'state', ' ', 'Coup', 'd', 'tat', 'executive', 'branch', 'constitution', ' ', 'Stein', 'went', 'Judges', 'Seattle', ' ', 'political', 'puppets', ' ', 'judiciary', ' ', 'political', 'pawns', 'Watch', 'interview', 'complete', 'statements', 'note', 'stark', 'contrast', 'rhetoric', 'leftist', 'media', 'pundits', 'neglect', 'note', 'court', 'blocked', 'Presidential', 'orders', 'immigration', 'past', 'discuss', 'legal', 'efficacy', 'halt', 'actual', 'text', 'Executive', 'Order', 'READ', 'TRUMP', 'NEWS', 'Century', 'Wire', 'Trump', 'FilesSUPPORT', 'WORK', 'SUBSCRIBING', 'MEMBER', '@21WIRE.TV']

![ ](https://img.shields.io/badge/Process%20%20-orange)

In [133]:
X_processed = []
for text in X4:
    text_pro = nlp(' '.join(text))
    lemmas = []
    for token in text_pro:
        lemmas.append(token.lemma_)
    X_processed.append(lemmas)

print(X_processed[0])

['Century', 'Wire', 'say', 'Ben', 'Stein', 'reputable', 'professor', 'Pepperdine', 'University', 'Hollywood', 'fame', 'appear', 'tv', 'show', 'film', 'Ferris', 'Bueller', 's', 'Day', 'provocative', 'statement', 'Judge', 'Jeanine', 'Pirro', 's', 'recently', 'discuss', 'halt', 'impose', 'President', 'Trump', 's', 'Executive', 'Order', 'travel', 'Stein', 'refer', 'judgement', 'ninth', 'Circuit', 'Court', 'Washington', 'state', '  ', 'Coup', 'd', 'tat', 'executive', 'branch', 'constitution', '  ', 'Stein', 'go', 'Judges', 'Seattle', '  ', 'political', 'puppet', '  ', 'judiciary', '  ', 'political', 'pawn', 'watch', 'interview', 'complete', 'statement', 'note', 'stark', 'contrast', 'rhetoric', 'leftist', 'medium', 'pundit', 'neglect', 'note', 'court', 'block', 'presidential', 'order', 'immigration', 'past', 'discuss', 'legal', 'efficacy', 'halt', 'actual', 'text', 'Executive', 'Order', 'READ', 'TRUMP', 'NEWS', 'Century', 'Wire', 'Trump', 'filessupport', 'work', 'subscribe', 'member', '@21wire.tv']

![ ](https://img.shields.io/badge/Vocabs%20%20-blue)

In [159]:
Vectors = []

for i in X_processed:
    vec = []
    
    for word in vocab:
        vec.append(i.count(word))
    
    Vectors.append(vec)

print(vocab)
print(Vectors[0])

[' ', '  ', '   ', '    ', '     ', '      ', '       ', ' \xa0\xa0\xa0\xa0 ', '"', "'", '...', '.https://youtu.be/gbjp8zxduwk', '1960', '1970', '1980s', '1990s', '2016Hillary', '2016of', '2016the', '2017featured', '2017me', '2017so', '@21wire.tv', '@AlxThomp', '@FoxNews', '@HillaryClinton', '@KristinnFR', '@Minnysconsin', '@aaldef', '@cnnpolitic', '@diamondandsilk', '@jonfavs', '@jonlovett', '@livelifecorazy', '@mccarthyryanj', '@realdonaldtrump', '@tvietor08', 'AAJA', 'AAPL.O', 'ABC', 'ADEN', 'AG', 'AL', 'ANO', 'ANTI', 'ASEAN', 'Abbasid', 'Abd', 'Abdulaziz', 'Abdullah', 'Abedin', 'Aberdeen', 'Act', 'Adam', 'Adelson', 'Aden', 'Advancing', 'Adviser', 'Advisory', 'Ahmed', 'Air', 'Alabama', 'Alex', 'Ali', 'Allison', 'Amendment', 'America', 'American', 'Americans', 'Amnesty', 'Anderson', 'Andrej', 'Angerer', 'Ankara', 'Antuam', 'Anuzis', 'Appeal', 'Apple', 'April', 'Arab', 'Arabia', 'Armed', 'Ash', 'Asia', 'Asian', 'AsianAmericanLegal', 'Assad', 'Assembly', 'Assistant', 'Association', 'Atlantic', 'Attorney', 'Aug.', 'August', 'Authority', 'Authorization', 'Aydaroos', 'Azerbaijan', 'BAGHDAD', 'BEIRUT', 'BRUSSELS', 'Babis', 'Bank', 'Bannon', 'Barack', 'Barnier', 'Bashar', 'Ben', 'Bend', 'Benjamin', 'Bernie', 'Betty', 'Bible', 'Bill', 'Blitzer', 'Bohuslav', 'Breitbart', 'Brexit', 'Bridge', 'Bridgegate', 'Britain', 'British', 'Brunswick', 'Brussels', 'Bryant', 'Budget', 'Bueller', 'Bush', 'Byrd', 'C.', 'CNN', 'CRISTOBAL', 'California', 'Caliphate', 'Cambodia', 'Cameron', 'Cami', 'Carolina', 'Carolinas', 'Carson', 'Carter', 'Category', 'Center', 'Century', 'Chairman', 'Championship', 'Charlotte', 'Cheney', 'Chiefs', 'China', 'Chinatown', 'Chinese', 'Chris', 'Christians', 'Christie', 'Circuit', 'Citing', 'Citizenship', 'City', 'Civil', 'Civilians', 'Claude', 'Clinton', 'Clintons', 'Club', 'Coast', 'Coats', 'Cohen', 'Cohn', 'Colin', 'Colombia', 'Comey', 'Commandments', 'Commission', 'Committee', 'Commodity', 'Communications', 'Community', 'Congress', 'Constitution', 'Conway', 'Cooper', 'Cooperative', 'Cornell', 'Corporation', 'Correspondent', 'Cory', 'Cotton', 'Council', 'Counsel', 'Counseling', 'County', 'Coup', 'Couple', 'Court', 'Criminal', 'Cristobal', 'Critics', 'Cruz', 'Current', 'Cyanide', 'Czech', 'D', 'D.C.', 'DOJ', 'DON’T', 'DPRK', 'Daesh', 'Daghr', 'Dan', 'David', 'Day', 'Deal', 'Debate', 'December', 'Defense', 'Delfin', 'Democrat', 'Democratic', 'Democrats', 'Dems', 'Department', 'Deputy', 'Describing', 'Details', 'Diamond', 'Dianne', 'Dick', 'Dina', 'Diplomat', 'Director', 'Dodd', 'Dominican', 'Don', 'Donald', 'Dr.', 'Drew', 'Drian', 'Dubya', 'Duke', 'Dunford', 'Duterte', 'EATING', 'ET', 'EU', 'East', 'Economic', 'Efforts', 'Elaine', 'Eleanor', 'Embassy', 'Enterprise', 'Equality', 'Esledy', 'Euphrates', 'Europe', 'European', 'Exchange', 'Executive', 'Ezra', 'FB.O', 'FBI', 'FL', 'FOX', 'FRANCISCO', 'Facebook', 'Factor', 'Farage', 'Featured', 'Feb.', 'February', 'Feinstein', 'Ferris', 'Financial', 'Flickr', 'Florida', 'Flynn', 'Force', 'Forces', 'Ford', 'Fort', 'Foundation', 'Fox', 'France', 'Frank', 'Freedom', 'Friday', 'Fund', 'Futures', 'G.', 'GLASGOW', 'GMT', 'GOOGL.O', 'GOP', 'Gabriel', 'Gangel', 'Garden', 'Gary', 'Gas', 'Gateway', 'General', 'Gentiloni', 'George', 'Georgia', 'Georgians', 'Germany', 'Getty', 'Ghad', 'Glasgow', 'God', 'Goebbels', 'Goldman', 'Golf', 'Google', 'Gov.', 'Governor', 'Graduation', 'Grand', 'Grijalva', 'Group', 'Guard', 'H-1B', 'H.R.', 'HATES', 'Hadi', 'Haiti', 'Hampshire', 'Hardline', 'Haslam', 'Healthcare', 'Heather', 'High', 'Hillary', 'Hitler', 'Holdings', 'Hollywood', 'Homeland', 'House', 'Houston', 'Houthis', 'Howell', 'Huckabee', 'Huma', 'Hurricane', 'IEEE', 'INFY.NS', 'ISIS', 'Illinois', 'Image', 'Images', 'Immigration', 'Improvements', 'Inc', 'Independence', 'India', 'Indiana', 'Industry', 'InfoWars', 'Information', 'Infosys', 'Instagram', 'Institute', 'Intelligence', 'International', 'Interstate', 'Iran', 'Iraq', 'Irma', 'Isis', 'Islamic', 'Islander', 'Islanders', 'Isle', 'Israel', 'Israeli', 'Istanbul', 'J', 'JERUSALEM', 'James', 'Jamie', 'Jan.', 'January', 'Japan', 'Jean', 'Jeanine', 'Jeff', 'Jeffrey', 'Jersey', 'Jerusalem', 'Jesse', 'Jesus', 'Jinping', 'Joe', 'John', 'Joint', 'Jones', 'Jose', 'Joseph', 'Josh', 'Journal', 'Journalists', 'Judge', 'Judges', 'Judicial', 'Judiciary', 'July', 'Juncker', 'June', 'Justice', 'K.T.', 'KKK', 'KNOWS', 'Kasich', 'Keene', 'Kellyanne', 'Khouang', 'King', 'Kislyak', 'Klan', 'Klansman', 'Klux', 'Korea', 'Korean', 'Kristinn', 'Ku', 'Kurdish', 'Kurdistan', 'Kurds', 'LGBT', 'LOL', 'LONDON', 'LUNCH', 'Labor', 'Lady', 'Lao', 'Laos', 'Lauderdale', 'Law', 'Le', 'Leeds', 'Legal', 'Legislation', 'Let', 'Lewis', 'Libya', 'Liverpool', 'Loehr', 'London', 'Lopez', 'Lord', 'Lorenzana', 'MARACAIBO', 'MISS', 'MSFT.O', 'MSN', 'Maduro', 'Maher', 'Major', 'Management', 'Mansour', 'Maracaibo', 'March', 'Marco', 'Maria', 'Marisol', 'Mark', 'Martin', 'Massachusetts', 'Massacre', 'McCain', 'McCarthy', 'McFarland', 'McMaster', 'McNamee', 'Means', 'Mediterranean', 'Melbourne', 'Metro', 'Miami', 'Mich.', 'Michael', 'Michel', 'Michelle', 'Michigan', 'Microsoft', 'Middle', 'Mike', 'Miller', 'Milos', 'Minds', 'Mines', 'Minister', 'Ministry', 'Mississippi', 'Missouri', 'Mitt', 'Mnuchin', 'Model', 'Monday', 'Moss', 'Mosul', 'Mr', 'Mr.', 'Mrs.', 'Mueller', 'Muflehi', 'Muslim', 'Muslims', 'N.Y.', 'NATIONS', 'NATO', 'NDAA', 'NEW', 'NEWS', 'NHC', 'NRA', 'NSC', 'NY', 'Nadella', 'Nashville', 'Nathan', 'National', 'Nations', 'Natural', 'Nauert', 'Needless', 'Netanyahu', 'Nevermind', 'New', 'News', 'Nicolas', 'Nigel', 'Night', 'Nixon', 'Norkis', 'North', 'Northeast', 'Nov.', 'November', 'O', 'ORC', 'Obama', 'ObamaCare', 'Obamacare', 'Obeid', 'Oberto', 'Oct.', 'October', 'Office', 'Ohler', 'Omni', 'Open', 'Order', 'Organization', 'Orlando', 'Orthotic', 'Oval', 'PARIS', 'PKK', 'PRAGUE', 'Pabon', 'Pacific', 'Paez', 'Palestinians', 'Paolo', 'Paris', 'Parliment', 'Parts', 'Party', 'Pastor', 'Paul', 'PayPal', 'Penalties', 'Pence', 'Peninsula', 'People', 'Pepperdine', 'Perry', 'Peter', 'Pharma', 'Phil', 'Philippines', 'Piggy', 'Pirro', 'Pod', 'Poland', 'Police', 'Policy', 'Politico', 'Politics', 'Post', 'Potential', 'Powell', 'Powys', 'Prayer', 'Preacher', 'President', 'Press', 'Priebus', 'Prime', 'Project', 'Prosthetic', 'Public', 'Puerto', 'Pundit', 'Pussygrabber', 'Pyongyang', 'Qarani', 'Quigg', 'R', 'READ', 'REFUSES', 'RESISTANCE', 'RNC', 'ROMEO', 'RUSSIA', 'Rabbu', 'Radio', 'Rapids', 'Raqqa', 'Raul', 'Readle', 'Regulatory', 'Reilly', 'Reince', 'Religion', 'Rep.', 'Representative', 'Representatives', 'Republic', 'Republican', 'Republicans', 'Resources', 'Reuters', 'Rex', 'Ricardo', 'Rice', 'Rick', 'Rico', 'Robert', 'Rod', 'Rodney', 'Rodrigo', 'Romney', 'Rose', 'Rosenstein', 'Roskam', 'Rossello', 'Rubio', 'Russia', 'Russians', 'Ryan', 'SAN', 'SCANDAL', 'SDF', 'Sachs', 'Sadly', 'Salas', 'Saleh', 'Salineville', 'San', 'Sanders', 'Santorum', 'Satellite', 'Saturday', 'Satya', 'Saudi', 'Saul', 'Savannah', 'Save', 'Schiff', 'School', 'Schools', 'Schwerin', 'Scotland', 'Seattle', 'Second', 'Secretary', 'Securities', 'Security', 'Selmayr', 'Sen.', 'Senate', 'Senator', 'Senators', 'Senior', 'Sept.', 'September', 'Sergei', 'Services', 'Sessions', 'Sheldon', 'Shelley', 'Shipyard', 'Sick', 'Sigmar', 'Silk', 'Simon', 'Sinpo', 'Smith', 'Sobotka', 'Social', 'South', 'Southern', 'Speaker', 'Special', 'Staff', 'State', 'States', 'Stein', 'Stephen', 'Steve', 'Steven', 'Street', 'Sunday', 'Sunni', 'Supremacist', 'Supreme', 'Susan', 'Syria', 'Syrian', 'Syrians', 'TRI.TO', 'TRUMP', 'Tajikistan', 'Taylor', 'Team', 'Ted', 'Tehran', 'Tennessee', 'Theresa', 'Thompson', 'Thomson', 'Thou', 'Thursday', 'Tillerson', 'Time', 'Times', 'TimesWatch', 'Today', 'Tom', 'Tower', 'Trading', 'Treasury', 'Trump', 'Tuesday', 'Turkey', 'Turnberry', 'Tweets', 'Twitter', 'U.N.', 'U.S.', 'U.S.-led', 'UK', 'UNITED', 'USA', 'USCIS', 'UXO', 'Union', 'United', 'University', 'Uwais', 'VIENTIANE', 'Venezuela', 'Venezuelans', 'Vice', 'Vientiane', 'Vietnam', 'Virginia', 'Visitor', 'Vote', 'WASHINGTON', 'WAY', 'WFB', 'WSB', 'WSJ', 'Wales', 'Wall', 'Wang', 'War', 'Washington', 'Watch', 'Watnick', 'Watter', 'Watters', 'Ways', 'Wednesday', 'West', 'Westchester', 'Westside', 'White', 'Wilson', 'Win', 'Wire', 'Wisconsin', 'Wisconsinites', 'Wolf', 'Workers', 'World', 'Xi', 'Xieng', 'YORK', 'YPG', 'Yale', 'Yemen', 'Yepsen', 'Yi', 'York', 'Yorker', 'YouTube', 'Yves', 'Zeman', 'Zubaydi', 'Zulia', 'a.m.', 'abandon', 'ability', 'able', 'abroad', 'absolute', 'abuse', 'accelerate', 'accept', 'access', 'accidentally', 'accord', 'account', 'accuse', 'achievement', 'acknowledge', 'acronym', 'act', 'acting', 'action', 'activate', 'actively', 'activist', 'activity', 'actual', 'actually', 'ad3media', 'add', 'addition', 'additional', 'address', 'adjacent', 'administration', 'administrator', 'adopt', 'adultery', 'advance', 'advanced', 'advice', 'advise', 'adviser', 'advocate', 'affect', 'african', 'afternoon', 'agency', 'aggressive', 'ago', 'agree', 'agreement', 'agriculture', 'ahead', 'aid', 'aide', 'aim', 'air', 'aircraft', 'al', 'alcohol', 'align', 'alike', 'allegation', 'alliance', 'allow', 'ally', 'alongside', 'alternative', 'ambassador', 'ambition', 'american', 'amid', 'ammunition', 'analysis', 'ancestral', 'andean', 'anger', 'announce', 'announcement', 'annual', 'anonymity', 'anonymously', 'answer', 'antagonistic', 'anti', 'antibiotic', 'anticipate', 'anticonvulsant', 'antiquity', 'apart', 'apiavote', 'apologize', 'apology', 'appal', 'apparent', 'appear', 'appearance', 'application', 'apply', 'appoint', 'appointee', 'appointment', 'approach', 'appropriately', 'approve', 'approximately', 'apron', 'arab', 'arabic', 'arcane', 'archaeological', 'architectural', 'area', 'argue', 'arguing', 'arm', 'armed', 'army', 'arrest', 'arrival', 'arrive', 'arsenal', 'article', 'ashame', 'asian', 'aside', 'asinine', 'ask', 'aspect', 'ass', 'assail', 'assault', 'assess', 'asshole', 'association', 'assume', 'assure', 'asylum', 'atheist', 'attack', 'attempt', 'attend', 'attendance', 'attention', 'attorney', 'audience', 'auspice', 'authority', 'authorize', 'avail', 'avidity', 'avoid', 'awakening', 'award', 'aware', 'away', 'back', 'background', 'backlash', 'backwards', 'bad', 'baffle', 'bailout', 'bait', 'balk', 'ballistic', 'ballot', 'ban', 'bank', 'banker', 'barrage', 'base', 'bash', 'basic', 'basically', 'basis', 'batch', 'bathroom', 'battle', 'bear', 'beat', 'beautiful', 'bed', 'begin', 'beginning', 'behave', 'behavior', 'belief', 'believe', 'bench', 'bend', 'benefit', 'beset', 'bid', 'big', 'bill', 'billion', 'billionaire', 'bin', 'bipartisan', 'bird', 'birth', 'bisexual', 'bitch', 'bitter', 'bizarre', 'black', 'blacklist', 'blame', 'blatant', 'blatantly', 'blind', 'blindly', 'block', 'blood', 'blow', 'blue', 'board', 'body', 'bog', 'bolivar', 'bomb', 'bombing', 'bonanza', 'bond', 'boon', 'border', 'box', 'boy', 'brag', 'branch', 'bravado', 'break', 'breakfast', 'briefing', 'brigade', 'bright', 'bring', 'british', 'broad', 'broker', 'brutal', 'buddy', 'build', 'building', 'bulk', 'bullet', 'bully', 'bunch', 'burdensome', 'bus', 'bush', 'business', 'businessman', 'buy', 'bypass', 'bypassing', 'c', 'cabinet', 'caliphate', 'call', 'calm', 'camp', 'campaign', 'campaign=', 'campus', 'cancel', 'candidacy', 'candidate', 'cap', 'capable', 'capably', 'capita', 'capital', 'capture', 'card', 'care', 'careful', 'caribbean', 'carry', 'case', 'casino', 'cast', 'casualty', 'catch', 'cause', 'caution', 'celebrate', 'center', 'central', 'century', 'ceo', 'ceremony', 'certain', 'certainly', 'certificate', 'chain', 'chair', 'chairman', 'challenge', 'chance', 'change', 'change?it', 'chapter', 'charge', 'cheap', 'check', 'cheek', 'chief', 'child', 'chime', 'chinatown', 'chinese', 'choice', 'choir', 'choose', 'chop', 'church', 'circle', 'circular', 'cite', 'citizen', 'city', 'civil', 'civilian', 'claim', 'clarify', 'class', 'classify', 'clear', 'clearing', 'clearly', 'client', 'close', 'closed', 'cluster', 'coalition', 'coast', 'coastal', 'code', 'coerce', 'coincidence', 'collapse', 'colleague', 'college', 'collusion', 'color', 'column', 'come', 'command', 'commander', 'commandment', 'comment', 'commentator', 'commercial', 'commit', 'commitment', 'committee', 'common', 'commonly', 'communication', 'communist', 'community', 'company', 'comparable', 'compare', 'compass', 'compassion', 'compassionate', 'compel', 'competitiveness', 'compile', 'complain', 'complete', 'completely', 'complex', 'component', 'compound', 'comprehensive', 'computer', 'concede', 'conceive', 'concentrate', 'concept', 'concern', 'concerned', 'conclude', 'condemn', 'condition', 'conduct', 'conference', 'confidant', 'confidence', 'confirm', 'confirmation', 'conflict', 'congregate', 'congressional', 'connection', 'conscience', 'conservative', 'consider', 'consideration', 'conspiracy', 'constitute', 'constitution', 'constitutional', 'construction', 'constructive', 'consumer', 'contact', 'contain', 'contaminate', 'continue', 'continued', 'contraband', 'contraceptive', 'contrast', 'contribute', 'control', 'controversial', 'controversy', 'convention', 'conventional', 'conversation', 'convict', 'conviction', 'convince', 'coordinate', 'copy', 'core', 'correct', 'corruption', 'cost', 'cough', 'couldn', 'counseling', 'counselor', 'count', 'counterpart', 'country', 'county', 'couple', 'course', 'court', 'cover', 'covet', 'craven', 'create', 'credential', 'criminal', 'crimp', 'crisis', 'critic', 'critical', 'criticism', 'criticize', 'crook', 'cross', 'crossover', 'crowd', 'crowded', 'cruel', 'crush', 'crystal', 'culture', 'currency', 'current', 'curry', 'cut', 'd', 'daily', 'damage', 'dancer', 'dangerous', 'datum', 'daughter', 'day', 'de', 'deadly', 'deal', 'death', 'debate', 'decade', 'decent', 'decide', 'decision', 'decisively', 'declare', 'decline', 'deductible', 'defeat', 'defend', 'defense', 'definitely', 'degree', 'demand', 'demeanor', 'democratic', 'denial', 'denuclearization', 'deny', 'department', 'departure', 'deplorable', 'deprive', 'depth', 'deputy', 'derail', 'derogatory', 'describe', 'deserve', 'desire', 'desperate', 'despicably', 'despite', 'destroy', 'destruction', 'detail', 'detect', 'deteriorate', 'determination', 'determine', 'devastate', 'devastating', 'devastation', 'develop', 'development', 'diabete', 'didn', 'diesel', 'difficult', 'diminish', 'dinner', 'direct', 'direction', 'director', 'dirty', 'disabled', 'disappoint', 'disaster', 'disavow', 'disclose', 'discolor', 'discourage', 'discriminate', 'discriminatory', 'discuss', 'discussion', 'disgusting', 'disharmony', 'dishearten', 'disintegrate', 'dislike', 'dismantle', 'dismiss', 'displace', 'dispute', 'dissatisfied', 'distinction', 'distribution', 'division', 'divisive', 'divorce', 'doctor', 'doesn', 'dollar', 'domestic', 'domination', 'don', 'donate', 'donation', 'donor', 'door', 'doubt', 'dozen', 'draft', 'dragon', 'drain', 'dramatic', 'drastically', 'draw', 'drawing', 'drift', 'drinking', 'drive', 'drop', 'drug', 'drum', 'dub', 'duel', 'duo', 'dupe', 'duty', 'dweller', 'early', 'earn', 'ease', 'easily', 'east', 'eastern', 'easy', 'echo', 'economic', 'economy', 'edition', 'editor', 'education', 'effect', 'effective', 'efficacy', 'effort', 'effortlessly', 'egotistical', 'eighteen', 'eighth', 'eighty', 'eighty%', 'ejection', 'elder', 'elderly', 'elect', 'election', 'electric', 'electricity', 'elevate', 'elimination', 'email', 'embark', 'embarrassed', 'embassy', 'embrace', 'emergency', 'emotional', 'empire', 'employ', 'employee', 'employers?they', 'encircle', 'enclave', 'encounter', 'encourage', 'end', 'endangered', 'endorse', 'endorsement', 'endure', 'enemy', 'energy', 'engine', 'engineer', 'english', 'ensure', 'enter', 'entire', 'entirely', 'entitle', 'entity', 'environment', 'equally', 'equivocation', 'escapade', 'escort', 'especially', 'essentially', 'establish', 'establishment', 'estate', 'estimate', 'ethic', 'ethnic', 'eulogize', 'evacuate', 'evacuation', 'evangelical', 'event', 'eventually', 'everyday', 'evidence', 'evolution', 'exacerbate', 'exact', 'exactly', 'examine', 'example', 'exchange', 'exclude', 'execute', 'execution', 'executive', 'exemplify', 'exerting', 'exile', 'exist', 'expand', 'expect', 'expensive', 'experimental', 'expert', 'expertise', 'expertly', 'explain', 'explanation', 'explicitly', 'explode', 'exploit', 'expose', 'express', 'extension', 'extensively', 'extrajudicial', 'extremely', 'eye', 'f*ck', 'face', 'facility', 'fact', 'faction', 'factor', 'fail', 'failing', 'failure', 'fair', 'faithfully', 'fake', 'fall', 'fallout', 'false', 'fame', 'familiar', 'family', 'far', 'farm', 'fascism', 'fast', 'father', 'favor', 'favorite', 'fear', 'feature', 'federal', 'feel', 'fellow', 'fervor', 'feud', 'fiduciary', 'field', 'fight', 'fighter', 'fighting', 'figure', 'filessupport', 'filing', 'fill', 'film', 'filter', 'final', 'finalize', 'finally', 'find', 'fine', 'fire', 'firearm', 'firm', 'fiscal', 'five.seven', 'fix', 'flag', 'flawed', 'flea', 'flee', 'flight', 'flood', 'flooding', 'floor', 'flourish', 'fluent', 'flung', 'fly', 'focus', 'folk', 'follow', 'follower', 'food', 'foot', 'foothold', 'force', 'foreign', 'foreigner', 'forever', 'forget', 'form', 'formal', 'formally', 'fortification', 'forward', 'foster', 'foul', 'fourteen', 'frankly', 'freedom', 'freeze', 'french', 'friend', 'frighten', 'frontrunner', 'fruit', 'fuel', 'fun', 'function', 'fund', 'funding', 'funeral', 'funny', 'future', 'gaffe', 'gain', 'gasoline', 'gay', 'gender', 'general', 'generally', 'gentle', 'genuine', 'german', 'gesture', 'get', 'getting', 'giddy', 'girl', 'give', 'glad', 'global', 'globalist', 'go', 'goal', 'going', 'golf', 'good', 'goon', 'government', 'governor', 'grab', 'grabber', 'grader', 'graduate', 'graduating', 'graduation', 'grand', 'grant', 'grapple', 'grasp', 'great', 'greed', 'green', 'grift', 'grifter', 'grip', 'grossly', 'ground', 'group', 'grouse', 'grow', 'guarantee', 'guard', 'gun', 'guy', 'half', 'halls', 'halt', 'hamper', 'hamstre', 'hand', 'handcuffed', 'handful', 'handicap', 'handily', 'hang', 'hanger', 'happen', 'happening', 'happy', 'hard', 'harm', 'hasn', 'hat', 'hate', 'have', 'having', 'head', 'headquarters', 'heal', 'health', 'healthcare', 'hear', 'hearing', 'heartless', 'heave', 'heavily', 'hegemonic', 'helicopter', 'hell', 'help', 'helped', 'helpful', 'hide', 'high', 'highly', 'hint', 'hire', 'historic', 'history', 'hit', 'hobble', 'hold', 'holder', 'hole', 'holy', 'home', 'homeland', 'honor', 'hope', 'horizon', 'horrendous', 'horrible', 'horrific', 'hospital', 'hospitalize', 'host', 'hostile', 'hostility', 'hotel', 'hour', 'house', 'housing', 'howell', 'https://t.co/84ZCW64hcE', 'https://t.co/ks2pg5igyc', 'https://t.co/utfr8wkome', 'hub', 'huge', 'hull', 'human', 'humanitarian', 'humid', 'humiliation', 'humor', 'hundred', 'hungary', 'hunt', 'hurricane', 'hurt', 'husband', 'hypocrisy', 'hypocrite', 'idea', 'identify', 'identity', 'ignorant', 'ignore', 'ignorne', 'illegal', 'illegally', 'illness', 'image', 'immediately', 'immigrant', 'immigrate', 'immigration', 'impact', 'impeachment', 'impediment', 'implication', 'implode', 'imploding', 'import', 'important', 'impose', 'inappropriate', 'incentive', 'incident', 'incite', 'incline', 'include', 'income', 'increase', 'increasingly', 'indian', 'indicate', 'individual', 'industry', 'inevitably', 'infighting', 'inflation', 'influence', 'influential', 'information', 'infrastructure', 'infringement', 'infuriate', 'inhabit', 'initial', 'initiate', 'initiative', 'injunction', 'injure', 'injury', 'innocent', 'inquire', 'inquired', 'inside', 'insist', 'install', 'instance', 'instead', 'instill', 'institute', 'insult', 'insurgency', 'insurgent', 'intelligence', 'intend', 'intense', 'intent', 'interest', 'interference', 'interim', 'internally', 'international', 'internet', 'interpretation', 'intervene', 'interview', 'intrigue', 'introduce', 'invasion', 'invest', 'investigate', 'investigation', 'investment', 'investor', 'involve', 'involved', 'involvement', 'iranian', 'iraqi', 'islamic', 'i

## BOW
>1-gram BOW

[![Naive Bayes](https://img.shields.io/badge/Naive_Bayes-classification-pink)](https://digitalpro.dev)

> Convert X docs to NumPy array

In [155]:
import numpy as np

X_vectors = np.array(Vectors) #define your Vectors
y_array = np.array(y)

> Split into train/test

In [156]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_vectors, y_array, test_size=0.2, random_state=42, stratify=y_array
)

> Train Naive Bayes classifier

In [157]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score, classification_report

nb = BernoulliNB()
nb.fit(X_train, y_train)    # Train

y_pred = nb.predict(X_test) # Predict

> Evaluate

In [160]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.7
              precision    recall  f1-score   support

           0       0.75      0.60      0.67         5
           1       0.67      0.80      0.73         5

    accuracy                           0.70        10
   macro avg       0.71      0.70      0.70        10
weighted avg       0.71      0.70      0.70        10